debug: false
data: '/srv/daemon-data'
api:
  host: '0.0.0.0'
  port: 8080
  ssl:
    enabled: false
    cert: ''
    key: ''
  upload_limit: 150000000
docker:
  container:
    user: ''
  network:
    interface: '172.18.0.1'
    name: 'pterodactyl_nw'
  update_images: true
  socket: '/var/run/docker.sock'
  timezone_path: '/etc/timezone'
set_permissions_on_boot: true
disk_check_timeout: 30
throttles:
  kill_at_count: 5
  decay: 10
  bytes: 4096
  check_interval: 100
remote: 'http://example.com'
token: 'test123'
